spring:
  batch:
    jdbc:
      initialize-schema: ALWAYS
  sql:
    init:
      platform: postgres
      continue-on-error: true
      mode: always
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://195.78.196.121/ocloud_cost
    username: ocloud_cost
    password: staging123!
    hikari:
      connectionTimeout: 20000
      maximumPoolSize: 5
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        type: trace
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show-sql: true
logging:
  level:
    org:
      springframework: ERROR
