spring:
  batch:
    jdbc:
      initialize-schema: ALWAYS
  sql:
    init:
      platform: postgres
      continue-on-error: true
      mode: always
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DB_CONNECTION_STRING}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    hikari:
      connectionTimeout: 20000
      maximumPoolSize: 5
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        type: trace
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show-sql: true
        jdbc:
          time_zone: UTC
logging:
  level:
    it: 
      irideos: DEBUG
    org:
      springframework: INFO
