## default connection pool
spring:
  batch:
    jdbc:
      initialize-schema: ALWAYS
  sql:
    init:
      platform: postgres
      continue-on-error: true
      mode: always
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/ocloud_cost
    username: docker
    password: SA
    hikari:
      connectionTimeout: 20000
      maximumPoolSize: 5
  jpa:
    properties:
      hibernate:
        ddl-auto: update
        type: trace
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        show-sql: true
        use_sql_comments: true
logging:
  level:
    org:
      springframework: ERROR
